# Generated by Django 6.0.3 on 2026-03-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed penalty amount charged per missed/late EMI installment', max_digits=10),
        ),
    ]
