# Generated by Django 6.0.3 on 2026-03-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_fine_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='fine_amount',
        ),
    ]
