# Generated by Django 6.0.3 on 2026-03-31 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loan_fine_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='emipayment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='loan_type',
            field=models.CharField(choices=[('vehicle', 'Vehicle Loan'), ('gold', 'Gold Loan')], default='vehicle', max_length=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Bike', 'Bike'), ('Scooter', 'Scooter'), ('Car', 'Car'), ('Auto', 'Auto'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='GoldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Chain', 'Chain'), ('Ring', 'Ring'), ('Earring', 'Earring'), ('Bangle', 'Bangle'), ('Necklace', 'Necklace'), ('Coin', 'Coin'), ('Bracelet', 'Bracelet'), ('Anklet', 'Anklet'), ('Other', 'Other')], default='Other', max_length=20)),
                ('item_description', models.CharField(blank=True, max_length=200)),
                ('weight_grams', models.DecimalField(decimal_places=3, max_digits=8)),
                ('purity', models.CharField(choices=[('24K', '24K'), ('22K', '22K'), ('18K', '18K'), ('916', '916 (22K)'), ('750', '750 (18K)'), ('Other', 'Other')], default='22K', max_length=10)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_items', to='loans.customer')),
            ],
        ),
    ]
