# Generated by Django 6.0.3 on 2026-04-17 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loanphoto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loanphoto',
            unique_together={('customer', 'photo_type')},
        ),
    ]
