# Generated by Django 6.0.3 on 2026-04-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loanphoto_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanphoto',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AlterUniqueTogether(
            name='loanphoto',
            unique_together=set(),
        ),
    ]
