# Generated by Django 6.0.3 on 2026-04-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_loanphoto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pan_card',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
