# Generated by Django 6.0.3 on 2026-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_customer_pan_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ml_collateral_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ml_collateral_type',
            field=models.CharField(blank=True, choices=[('Land', 'Land'), ('Building', 'Building'), ('Plot', 'Plot'), ('Agricultural Land', 'Agricultural Land'), ('Commercial Property', 'Commercial Property'), ('Residential Property', 'Residential Property'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='ml_collateral_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='customer',
            name='ml_document_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='ml_property_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ml_survey_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loan_type',
            field=models.CharField(choices=[('vehicle', 'Vehicle Loan'), ('gold', 'Gold Loan'), ('ml', 'ML Loan')], default='vehicle', max_length=10),
        ),
    ]
