# Generated by Django 6.0.3 on 2026-04-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_customer_ml_collateral_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='proof_description',
            field=models.TextField(blank=True, help_text='Proof / documents collected from the customer. e.g. RC Book, Keys (vehicle) | Gold bill, certificate (gold) | Sale deed, Patta (ML).'),
        ),
    ]
