# Generated by Django 6.0.3 on 2026-04-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_dailyledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='document_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='One-time charge deducted before handing over cash. Loan agreement is still for the full loan_amount. Customer actually receives loan_amount − document_charge. Automatically recorded as a credit entry in DailyLedger.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyledger',
            name='source',
            field=models.CharField(choices=[('emi_payment', 'EMI Payment'), ('document_charge', 'Document Charge'), ('manual', 'Manual Entry')], default='manual', max_length=20),
        ),
    ]
