# Generated by Django 6.0.3 on 2026-04-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_loan_document_charge_alter_dailyledger_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyledger',
            name='source',
            field=models.CharField(choices=[('emi_payment', 'EMI Payment'), ('document_charge', 'Document Charge'), ('loan_disbursement', 'Loan Disbursement'), ('manual', 'Manual Entry')], default='manual', max_length=20),
        ),
    ]
